---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-forward-backend
  namespace: argocd
  labels:
    app: pod-forward-backend
    app.kubernetes.io/name: pod-forward-backend
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-forward-backend
  template:
    metadata:
      labels:
        app: pod-forward-backend
    spec:
      serviceAccountName: pod-forward-backend
      containers:
      - name: pod-forward-backend
        image: ghcr.io/ghcetraro/argocd-extension-pod-forward-backend/pod-forward-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pod-forward-backend
  namespace: argocd
  labels:
    app: pod-forward-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pod-forward-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-forward-backend
  namespace: argocd
  labels:
    app: pod-forward-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-forward-backend
  labels:
    app: pod-forward-backend
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-forward-backend
  labels:
    app: pod-forward-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-forward-backend
subjects:
- kind: ServiceAccount
  name: pod-forward-backend
  namespace: argocd
